version: '3'
services:

  server:
    build:
      context: server/
      dockerfile: Dockerfile.api
    container_name: server
    ports:
      - "3000:3000"
    networks:
      - deploy_network
    volumes:
      - ./server:/server
      - ./data:/data

  myapp:
    build:
      context: app/
    container_name: app
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    command: ["streamlit", "run", "--server.address", "0.0.0.0", "app.py"]
    volumes:
      - ./app:/app
      - ./data:/data

networks:
  deploy_network:
    driver: bridge